#
# Makefile for MStar NAND device drivers.
#

# general options
EXTRA_CFLAGS      +=  -Idrivers/mstar/include/sys/common
EXTRA_CFLAGS      +=  -Idrivers/mstar/include
EXTRA_CFLAGS      +=  -Idrivers/mstar/mspi

# specific options
EXTRA_CFLAGS      +=  -DRED_LION

# files
obj-y  += halMSPI.o
